var searchData=
[
  ['editorutilities_472',['EditorUtilities',['../namespace_t_m_pro_1_1_editor_utilities.html',1,'TMPro']]],
  ['spriteassetutilities_473',['SpriteAssetUtilities',['../namespace_t_m_pro_1_1_sprite_asset_utilities.html',1,'TMPro']]],
  ['tagattribute_474',['TagAttribute',['../struct_t_m_pro_1_1_tag_attribute.html',1,'TMPro']]],
  ['tagvaluetype_475',['TagValueType',['../namespace_t_m_pro.html#a9d72007c13ac0bf341a0ea96f1175f0f',1,'TMPro']]],
  ['template_476',['template',['../class_t_m_pro_1_1_t_m_p___dropdown.html#a6ab2bc63f80032f0d78d195fac730d5f',1,'TMPro::TMP_Dropdown']]],
  ['text_477',['text',['../class_t_m_pro_1_1_t_m_p___text.html#a98a04e5078612c0586472bd510f91f5c',1,'TMPro.TMP_Text.text()'],['../class_t_m_pro_1_1_t_m_p___input_field.html#ab89ad02ff00c4c076c5bd3303528e5de',1,'TMPro.TMP_InputField.text()'],['../class_t_m_pro_1_1_t_m_p___dropdown_1_1_option_data.html#aaa4fe424c6a5503e154e9861e3bfd122',1,'TMPro.TMP_Dropdown.OptionData.text()']]],
  ['textbounds_478',['textBounds',['../class_t_m_pro_1_1_t_m_p___text.html#aa61944e2c4973b8b7b07df8d8f15e2c9',1,'TMPro::TMP_Text']]],
  ['textcontainer_479',['textContainer',['../class_t_m_pro_1_1_text_mesh_pro.html#a439781d7ef6aa16cd7ee1695ebb8f29f',1,'TMPro::TextMeshPro']]],
  ['textcontainer_480',['TextContainer',['../class_t_m_pro_1_1_text_container.html',1,'TMPro']]],
  ['textinfo_481',['textInfo',['../class_t_m_pro_1_1_t_m_p___text.html#a4b2d23d558ff8f9aecf5814f046bcef6',1,'TMPro::TMP_Text']]],
  ['textmeshpro_482',['textMeshPro',['../class_t_m_pro_1_1_text_container.html#adf8a50e4acdd21586b22c5b0939cd3bc',1,'TMPro::TextContainer']]],
  ['textmeshpro_483',['TextMeshPro',['../class_t_m_pro_1_1_text_mesh_pro.html',1,'TMPro']]],
  ['textmeshprougui_484',['TextMeshProUGUI',['../class_t_m_pro_1_1_text_mesh_pro_u_g_u_i.html',1,'TMPro']]],
  ['textrenderflags_485',['TextRenderFlags',['../namespace_t_m_pro.html#ac5a571bdd8e4873a73f2c05b62feff0e',1,'TMPro']]],
  ['textselectionevent_486',['TextSelectionEvent',['../class_t_m_pro_1_1_t_m_p___input_field_1_1_text_selection_event.html',1,'TMPro::TMP_InputField']]],
  ['texturepacker_487',['TexturePacker',['../class_t_m_pro_1_1_sprite_asset_utilities_1_1_texture_packer.html',1,'TMPro::SpriteAssetUtilities']]],
  ['tintallsprites_488',['tintAllSprites',['../class_t_m_pro_1_1_t_m_p___text.html#a3af8d969cc20cf4fac2b48fc057737a1',1,'TMPro::TMP_Text']]],
  ['tmp_5fasset_489',['TMP_Asset',['../class_t_m_pro_1_1_t_m_p___asset.html',1,'TMPro']]],
  ['tmp_5fbaseeditorpanel_490',['TMP_BaseEditorPanel',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___base_editor_panel.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fbaseshadergui_491',['TMP_BaseShaderGUI',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___base_shader_g_u_i.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fbitmapshadergui_492',['TMP_BitmapShaderGUI',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___bitmap_shader_g_u_i.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fcharacter_493',['TMP_Character',['../class_t_m_pro_1_1_t_m_p___character.html#a619c065318ac716fb0d66217ac866a9b',1,'TMPro.TMP_Character.TMP_Character(uint unicode, Glyph glyph)'],['../class_t_m_pro_1_1_t_m_p___character.html#a93893b221a4c7eab5c45cc564e4f6219',1,'TMPro.TMP_Character.TMP_Character()'],['../class_t_m_pro_1_1_t_m_p___character.html',1,'TMPro.TMP_Character']]],
  ['tmp_5fcharacterinfo_494',['TMP_CharacterInfo',['../struct_t_m_pro_1_1_t_m_p___character_info.html',1,'TMPro']]],
  ['tmp_5fcharacterpropertydrawer_495',['TMP_CharacterPropertyDrawer',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___character_property_drawer.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fcolorgradient_496',['TMP_ColorGradient',['../class_t_m_pro_1_1_t_m_p___color_gradient.html#acfc78a5c6cb6511ef9f6b9c8c13d1748',1,'TMPro.TMP_ColorGradient.TMP_ColorGradient(Color color0, Color color1, Color color2, Color color3)'],['../class_t_m_pro_1_1_t_m_p___color_gradient.html#ad8a5ef960c6adff7252e289593bbcbd2',1,'TMPro.TMP_ColorGradient.TMP_ColorGradient(Color color)'],['../class_t_m_pro_1_1_t_m_p___color_gradient.html#ade6a10f2d14048890c9e4d93c8f33012',1,'TMPro.TMP_ColorGradient.TMP_ColorGradient()'],['../class_t_m_pro_1_1_t_m_p___color_gradient.html',1,'TMPro.TMP_ColorGradient']]],
  ['tmp_5fcolorgradienteditor_497',['TMP_ColorGradientEditor',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___color_gradient_editor.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fcontextmenus_498',['TMP_ContextMenus',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___context_menus.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fdropdown_499',['TMP_Dropdown',['../class_t_m_pro_1_1_t_m_p___dropdown.html',1,'TMPro']]],
  ['tmp_5feditorcoroutine_500',['TMP_EditorCoroutine',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___editor_coroutine.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5feditorpanel_501',['TMP_EditorPanel',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___editor_panel.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5feditortests_502',['TMP_EditorTests',['../class_t_m_pro_1_1_t_m_p___editor_tests.html',1,'TMPro']]],
  ['tmp_5ffontasset_503',['TMP_FontAsset',['../class_t_m_pro_1_1_t_m_p___font_asset.html',1,'TMPro']]],
  ['tmp_5ffontasseteditor_504',['TMP_FontAssetEditor',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___font_asset_editor.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5ffontassetutilities_505',['TMP_FontAssetUtilities',['../class_t_m_pro_1_1_t_m_p___font_asset_utilities.html',1,'TMPro']]],
  ['tmp_5ffontfeaturetable_506',['TMP_FontFeatureTable',['../class_t_m_pro_1_1_t_m_p___font_feature_table.html',1,'TMPro']]],
  ['tmp_5ffontstylestack_507',['TMP_FontStyleStack',['../struct_t_m_pro_1_1_t_m_p___font_style_stack.html',1,'TMPro']]],
  ['tmp_5ffontweightpair_508',['TMP_FontWeightPair',['../struct_t_m_pro_1_1_t_m_p___font_weight_pair.html',1,'TMPro']]],
  ['tmp_5fglyph_509',['TMP_Glyph',['../class_t_m_pro_1_1_t_m_p___glyph.html',1,'TMPro']]],
  ['tmp_5fglyphadjustmentrecord_510',['TMP_GlyphAdjustmentRecord',['../struct_t_m_pro_1_1_t_m_p___glyph_adjustment_record.html#af771712249b63c81fe4656d781d87bac',1,'TMPro.TMP_GlyphAdjustmentRecord.TMP_GlyphAdjustmentRecord()'],['../struct_t_m_pro_1_1_t_m_p___glyph_adjustment_record.html',1,'TMPro.TMP_GlyphAdjustmentRecord']]],
  ['tmp_5fglyphpairadjustmentrecord_511',['TMP_GlyphPairAdjustmentRecord',['../class_t_m_pro_1_1_t_m_p___glyph_pair_adjustment_record.html#a781093da614822d0cec95ec6598f3d4e',1,'TMPro.TMP_GlyphPairAdjustmentRecord.TMP_GlyphPairAdjustmentRecord()'],['../class_t_m_pro_1_1_t_m_p___glyph_pair_adjustment_record.html',1,'TMPro.TMP_GlyphPairAdjustmentRecord']]],
  ['tmp_5fglyphpairadjustmentrecordpropertydrawer_512',['TMP_GlyphPairAdjustmentRecordPropertyDrawer',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___glyph_pair_adjustment_record_property_drawer.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fglyphpropertydrawer_513',['TMP_GlyphPropertyDrawer',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___glyph_property_drawer.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fglyphvaluerecord_514',['TMP_GlyphValueRecord',['../struct_t_m_pro_1_1_t_m_p___glyph_value_record.html#a4f702e2f263a2e6e9cf005416bd9ac8f',1,'TMPro.TMP_GlyphValueRecord.TMP_GlyphValueRecord()'],['../struct_t_m_pro_1_1_t_m_p___glyph_value_record.html',1,'TMPro.TMP_GlyphValueRecord']]],
  ['tmp_5finputfield_515',['TMP_InputField',['../class_t_m_pro_1_1_t_m_p___input_field.html',1,'TMPro']]],
  ['tmp_5finputfieldeditor_516',['TMP_InputFieldEditor',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___input_field_editor.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5finputvalidator_517',['TMP_InputValidator',['../class_t_m_pro_1_1_t_m_p___input_validator.html',1,'TMPro']]],
  ['tmp_5flineinfo_518',['TMP_LineInfo',['../struct_t_m_pro_1_1_t_m_p___line_info.html',1,'TMPro']]],
  ['tmp_5flinkinfo_519',['TMP_LinkInfo',['../struct_t_m_pro_1_1_t_m_p___link_info.html',1,'TMPro']]],
  ['tmp_5fmeshinfo_520',['TMP_MeshInfo',['../struct_t_m_pro_1_1_t_m_p___mesh_info.html#a34bbcd82d7626fdc9d7598eac632f2b9',1,'TMPro.TMP_MeshInfo.TMP_MeshInfo(Mesh mesh, int size, bool isVolumetric)'],['../struct_t_m_pro_1_1_t_m_p___mesh_info.html#a457cf31e803ba04bcbc37a88fe70ab12',1,'TMPro.TMP_MeshInfo.TMP_MeshInfo(Mesh mesh, int size)'],['../struct_t_m_pro_1_1_t_m_p___mesh_info.html',1,'TMPro.TMP_MeshInfo']]],
  ['tmp_5fpackageutilities_521',['TMP_PackageUtilities',['../class_t_m_pro_1_1_t_m_p___package_utilities.html',1,'TMPro']]],
  ['tmp_5fpageinfo_522',['TMP_PageInfo',['../struct_t_m_pro_1_1_t_m_p___page_info.html',1,'TMPro']]],
  ['tmp_5fpostbuildprocesshandler_523',['TMP_PostBuildProcessHandler',['../class_t_m_pro_1_1_t_m_p___post_build_process_handler.html',1,'TMPro']]],
  ['tmp_5fprojectconversionutility_524',['TMP_ProjectConversionUtility',['../class_t_m_pro_1_1_t_m_p___project_conversion_utility.html',1,'TMPro']]],
  ['tmp_5fresourcesloader_525',['TMP_ResourcesLoader',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___resources_loader.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5frichtexttagstack_526',['TMP_RichTextTagStack',['../struct_t_m_pro_1_1_t_m_p___rich_text_tag_stack.html#aaa1a320d4e3978f5cdaf72109307c61a',1,'TMPro.TMP_RichTextTagStack.TMP_RichTextTagStack(int capacity)'],['../struct_t_m_pro_1_1_t_m_p___rich_text_tag_stack.html#a4a6693a653816e4fcd2ce00d76e17744',1,'TMPro.TMP_RichTextTagStack.TMP_RichTextTagStack(T[] tagStack)'],['../struct_t_m_pro_1_1_t_m_p___rich_text_tag_stack.html',1,'TMPro.TMP_RichTextTagStack&lt; T &gt;']]],
  ['tmp_5frichtexttagstack_3c_20color32_20_3e_527',['TMP_RichTextTagStack&lt; Color32 &gt;',['../struct_t_m_pro_1_1_t_m_p___rich_text_tag_stack.html',1,'TMPro']]],
  ['tmp_5frichtexttagstack_3c_20float_20_3e_528',['TMP_RichTextTagStack&lt; float &gt;',['../struct_t_m_pro_1_1_t_m_p___rich_text_tag_stack.html',1,'TMPro']]],
  ['tmp_5frichtexttagstack_3c_20fontweight_20_3e_529',['TMP_RichTextTagStack&lt; FontWeight &gt;',['../struct_t_m_pro_1_1_t_m_p___rich_text_tag_stack.html',1,'TMPro']]],
  ['tmp_5frichtexttagstack_3c_20int_20_3e_530',['TMP_RichTextTagStack&lt; int &gt;',['../struct_t_m_pro_1_1_t_m_p___rich_text_tag_stack.html',1,'TMPro']]],
  ['tmp_5frichtexttagstack_3c_20textalignmentoptions_20_3e_531',['TMP_RichTextTagStack&lt; TextAlignmentOptions &gt;',['../struct_t_m_pro_1_1_t_m_p___rich_text_tag_stack.html',1,'TMPro']]],
  ['tmp_5frichtexttagstack_3c_20tmpro_3a_3amaterialreference_20_3e_532',['TMP_RichTextTagStack&lt; TMPro::MaterialReference &gt;',['../struct_t_m_pro_1_1_t_m_p___rich_text_tag_stack.html',1,'TMPro']]],
  ['tmp_5frichtexttagstack_3c_20tmpro_3a_3atmp_5fcolorgradient_20_3e_533',['TMP_RichTextTagStack&lt; TMPro::TMP_ColorGradient &gt;',['../struct_t_m_pro_1_1_t_m_p___rich_text_tag_stack.html',1,'TMPro']]],
  ['tmp_5fruntimetests_534',['TMP_RuntimeTests',['../class_t_m_pro_1_1_t_m_p___runtime_tests.html',1,'TMPro']]],
  ['tmp_5fscrollbareventhandler_535',['TMP_ScrollbarEventHandler',['../class_t_m_pro_1_1_t_m_p___scrollbar_event_handler.html',1,'TMPro']]],
  ['tmp_5fsdfshadergui_536',['TMP_SDFShaderGUI',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___s_d_f_shader_g_u_i.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fselectioncaret_537',['TMP_SelectionCaret',['../class_t_m_pro_1_1_t_m_p___selection_caret.html',1,'TMPro']]],
  ['tmp_5fserializedpropertyholder_538',['TMP_SerializedPropertyHolder',['../class_t_m_pro_1_1_t_m_p___serialized_property_holder.html',1,'TMPro']]],
  ['tmp_5fsettings_539',['TMP_Settings',['../class_t_m_pro_1_1_t_m_p___settings.html',1,'TMPro']]],
  ['tmp_5fsettingseditor_540',['TMP_SettingsEditor',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___settings_editor.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fsprite_541',['TMP_Sprite',['../class_t_m_pro_1_1_t_m_p___sprite.html',1,'TMPro']]],
  ['tmp_5fspriteanimator_542',['TMP_SpriteAnimator',['../class_t_m_pro_1_1_t_m_p___sprite_animator.html',1,'TMPro']]],
  ['tmp_5fspriteasset_543',['TMP_SpriteAsset',['../class_t_m_pro_1_1_t_m_p___sprite_asset.html',1,'TMPro']]],
  ['tmp_5fspriteasseteditor_544',['TMP_SpriteAssetEditor',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___sprite_asset_editor.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fspriteassetimporter_545',['TMP_SpriteAssetImporter',['../class_t_m_pro_1_1_t_m_p___sprite_asset_importer.html',1,'TMPro']]],
  ['tmp_5fspritecharacter_546',['TMP_SpriteCharacter',['../class_t_m_pro_1_1_t_m_p___sprite_character.html#a1959feaba9440fa7b3861f8faaa938c9',1,'TMPro.TMP_SpriteCharacter.TMP_SpriteCharacter()'],['../class_t_m_pro_1_1_t_m_p___sprite_character.html#aa92949aefc58deb87fcde3b5e1c4a336',1,'TMPro.TMP_SpriteCharacter.TMP_SpriteCharacter(uint unicode, TMP_SpriteGlyph glyph)'],['../class_t_m_pro_1_1_t_m_p___sprite_character.html',1,'TMPro.TMP_SpriteCharacter']]],
  ['tmp_5fspritecharacterpropertydrawer_547',['TMP_SpriteCharacterPropertyDrawer',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___sprite_character_property_drawer.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fspriteglyph_548',['TMP_SpriteGlyph',['../class_t_m_pro_1_1_t_m_p___sprite_glyph.html#a69ba65978c19f482a446a3d2dea32753',1,'TMPro.TMP_SpriteGlyph.TMP_SpriteGlyph(uint index, GlyphMetrics metrics, GlyphRect glyphRect, float scale, int atlasIndex)'],['../class_t_m_pro_1_1_t_m_p___sprite_glyph.html#ac8f2331687440c1eacbd707c5a2d4a7d',1,'TMPro.TMP_SpriteGlyph.TMP_SpriteGlyph(uint index, GlyphMetrics metrics, GlyphRect glyphRect, float scale, int atlasIndex, Sprite sprite)'],['../class_t_m_pro_1_1_t_m_p___sprite_glyph.html',1,'TMPro.TMP_SpriteGlyph']]],
  ['tmp_5fspriteglyphpropertydrawer_549',['TMP_SpriteGlyphPropertyDrawer',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___sprite_glyph_property_drawer.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fspriteinfo_550',['TMP_SpriteInfo',['../struct_t_m_pro_1_1_t_m_p___sprite_info.html',1,'TMPro']]],
  ['tmp_5fstyle_551',['TMP_Style',['../class_t_m_pro_1_1_t_m_p___style.html',1,'TMPro']]],
  ['tmp_5fstyleeditor_552',['TMP_StyleEditor',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___style_editor.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fstylesheet_553',['TMP_StyleSheet',['../class_t_m_pro_1_1_t_m_p___style_sheet.html',1,'TMPro']]],
  ['tmp_5fsubmesh_554',['TMP_SubMesh',['../class_t_m_pro_1_1_t_m_p___sub_mesh.html',1,'TMPro']]],
  ['tmp_5fsubmesh_5feditor_555',['TMP_SubMesh_Editor',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___sub_mesh___editor.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fsubmeshui_556',['TMP_SubMeshUI',['../class_t_m_pro_1_1_t_m_p___sub_mesh_u_i.html',1,'TMPro']]],
  ['tmp_5fsubmeshui_5feditor_557',['TMP_SubMeshUI_Editor',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___sub_mesh_u_i___editor.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5ftext_558',['TMP_Text',['../class_t_m_pro_1_1_t_m_p___text.html',1,'TMPro']]],
  ['tmp_5ftextalignmentdrawer_559',['TMP_TextAlignmentDrawer',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___text_alignment_drawer.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5ftextelement_560',['TMP_TextElement',['../class_t_m_pro_1_1_t_m_p___text_element.html',1,'TMPro']]],
  ['tmp_5ftextelement_5flegacy_561',['TMP_TextElement_Legacy',['../class_t_m_pro_1_1_t_m_p___text_element___legacy.html',1,'TMPro']]],
  ['tmp_5ftextinfo_562',['TMP_TextInfo',['../class_t_m_pro_1_1_t_m_p___text_info.html',1,'TMPro']]],
  ['tmp_5ftextparsingutilities_563',['TMP_TextParsingUtilities',['../class_t_m_pro_1_1_t_m_p___text_parsing_utilities.html',1,'TMPro']]],
  ['tmp_5fuieditorpanel_564',['TMP_UiEditorPanel',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_p___ui_editor_panel.html',1,'TMPro::EditorUtilities']]],
  ['tmp_5fupdatemanager_565',['TMP_UpdateManager',['../class_t_m_pro_1_1_t_m_p___update_manager.html#aac91ee76bdd5a4fe9e77536d51a644b8',1,'TMPro.TMP_UpdateManager.TMP_UpdateManager()'],['../class_t_m_pro_1_1_t_m_p___update_manager.html',1,'TMPro.TMP_UpdateManager']]],
  ['tmp_5fupdateregistry_566',['TMP_UpdateRegistry',['../class_t_m_pro_1_1_t_m_p___update_registry.html#ace9d173b85d91abac839f7fb70b73b9f',1,'TMPro.TMP_UpdateRegistry.TMP_UpdateRegistry()'],['../class_t_m_pro_1_1_t_m_p___update_registry.html',1,'TMPro.TMP_UpdateRegistry']]],
  ['tmp_5fvertex_567',['TMP_Vertex',['../struct_t_m_pro_1_1_t_m_p___vertex.html',1,'TMPro']]],
  ['tmp_5fvertexdataupdateflags_568',['TMP_VertexDataUpdateFlags',['../namespace_t_m_pro.html#a517464fab2ef7ff5b9658d2acaf49a57',1,'TMPro']]],
  ['tmp_5fwordinfo_569',['TMP_WordInfo',['../struct_t_m_pro_1_1_t_m_p___word_info.html',1,'TMPro']]],
  ['tmpro_570',['TMPro',['../namespace_t_m_pro.html',1,'']]],
  ['tmpro_5ffontassetcreatorwindow_571',['TMPro_FontAssetCreatorWindow',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_pro___font_asset_creator_window.html',1,'TMPro::EditorUtilities']]],
  ['tmpro_5ftextcontainereditor_572',['TMPro_TextContainerEditor',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_pro___text_container_editor.html',1,'TMPro::EditorUtilities']]],
  ['tmpro_5ftexturepostprocessor_573',['TMPro_TexturePostProcessor',['../class_t_m_pro_1_1_editor_utilities_1_1_t_m_pro___texture_post_processor.html',1,'TMPro::EditorUtilities']]],
  ['tolowerasciifast_574',['ToLowerASCIIFast',['../class_t_m_pro_1_1_t_m_p___text_parsing_utilities.html#ae8727745fb67672cd72e7cb3e2cd12f8',1,'TMPro.TMP_TextParsingUtilities.ToLowerASCIIFast(char c)'],['../class_t_m_pro_1_1_t_m_p___text_parsing_utilities.html#aaff8cac98f068d2b194b6498f1671ef3',1,'TMPro.TMP_TextParsingUtilities.ToLowerASCIIFast(uint c)']]],
  ['touchscreenkeyboardevent_575',['TouchScreenKeyboardEvent',['../class_t_m_pro_1_1_t_m_p___input_field_1_1_touch_screen_keyboard_event.html',1,'TMPro::TMP_InputField']]],
  ['toupperasciifast_576',['ToUpperASCIIFast',['../class_t_m_pro_1_1_t_m_p___text_parsing_utilities.html#a57e8e32bda8815e697db41cb4820d56a',1,'TMPro.TMP_TextParsingUtilities.ToUpperASCIIFast(char c)'],['../class_t_m_pro_1_1_t_m_p___text_parsing_utilities.html#ab51375da32109d357129a13219174803',1,'TMPro.TMP_TextParsingUtilities.ToUpperASCIIFast(uint c)']]],
  ['transform_577',['transform',['../class_t_m_pro_1_1_text_mesh_pro.html#a6748c431d98cca84eb55e16ad2a636ac',1,'TMPro.TextMeshPro.transform()'],['../class_t_m_pro_1_1_t_m_p___text.html#aa0aea09b889f063a8bea42ab981d0569',1,'TMPro.TMP_Text.transform()']]],
  ['tryaddcharacters_578',['TryAddCharacters',['../class_t_m_pro_1_1_t_m_p___font_asset.html#a488b2341f857f3693d07690073f81697',1,'TMPro.TMP_FontAsset.TryAddCharacters(uint[] unicodes)'],['../class_t_m_pro_1_1_t_m_p___font_asset.html#a3d6e7cfba34d30def8eac058f40d9f91',1,'TMPro.TMP_FontAsset.TryAddCharacters(uint[] unicodes, out uint[] missingUnicodes)'],['../class_t_m_pro_1_1_t_m_p___font_asset.html#a72d41f80fdf9dd16369125ea0ac1c151',1,'TMPro.TMP_FontAsset.TryAddCharacters(string characters)'],['../class_t_m_pro_1_1_t_m_p___font_asset.html#a0256954b0c39ba295abb6602739e826f',1,'TMPro.TMP_FontAsset.TryAddCharacters(string characters, out string missingCharacters)']]],
  ['trygetcolorgradientpreset_579',['TryGetColorGradientPreset',['../class_t_m_pro_1_1_material_reference_manager.html#a61de4a348042d6714254fd9558f8f632',1,'TMPro::MaterialReferenceManager']]],
  ['trygetfontasset_580',['TryGetFontAsset',['../class_t_m_pro_1_1_material_reference_manager.html#aea90526985cf5081a931bfbc4d36af81',1,'TMPro::MaterialReferenceManager']]],
  ['trygetmaterial_581',['TryGetMaterial',['../class_t_m_pro_1_1_material_reference_manager.html#a4826b2b5ac5de579423e0eaee6955dfc',1,'TMPro::MaterialReferenceManager']]],
  ['trygetspriteasset_582',['TryGetSpriteAsset',['../class_t_m_pro_1_1_material_reference_manager.html#a134f55b51c7660176516e2fe3b71d4ae',1,'TMPro::MaterialReferenceManager']]]
];
